#!/bin/bash
current_branch() {
    git branch --no-color | grep '^\* ' | grep -v 'no branch' | sed 's/^* //g'
}

git_dir() {
    git rev-parse --git-dir
}

load_settings() {
    export git_dir=$(git rev-parse --git-dir 2>/dev/null)
    export develop_branch=$(git config --get trello.branch.develop)
    export release_branch=$(git config --get trello.branch.release)
    export basebranchweb=$(git config --get trello.basebranchweb)
}

init() {
    load_settings
    echo ""
    echo "* You are about to set git local variables for trello."
    if test -z "$develop_branch"; then
        develop_branch=$(git branch | grep -w develop | tr '*' ' ' | head -1)
        develop_branch=$(echo $develop_branch)
    fi
    if test -z "$release_branch"; then
        release_branch=$(git branch | grep -w master | tr '*' ' ' | head -1)
        release_branch=$(echo $release_branch)
    fi
    echo ""
    echo "* Branches for feature base."
    PS3="Choose feature base branch (e.g.:$develop_branch): "
    select develop_branch in $(git branch | grep -v '/' | tr '*' ' ')
    do
        if git branch -l | grep -q $develop_branch 2>/dev/null; then
            break
        fi
    done
    echo ""
    echo "* Branches for hotfix base."
    PS3="Choose hotfix base branch (e.g.:$release_branch): "
    select release_branch in $(git branch | grep -v '/' | tr '*' ' ')
    do
        if git branch -l | grep -q $release_branch 2>/dev/null; then
            break
        fi
    done

    hint=
    savedbase="$basebranchweb"
    echo ""
    echo "* We need to set branch web url."
    if test -n "$basebranchweb"; then
        echo "* current: $basebranchweb"
        hint=" (Empty to keep current value)"
    fi
    echo ""
    echo "  Let me know your $develop_branch branch's web page (ends with $develop_branch)"
    echo "  For e.g: https://bitbucket.org/your-org/your-repo/branch/$develop_branch"
    while true
    do
        echo ""
        read -p "* Web page for $develop_branch branch$hint: " basebranchweb
        if test -z "$basebranchweb"; then
            if test -n "$savedbase"; then
                basebranchweb="$savedbase"
                break
            fi
            continue
        fi
        basebranchweb=${basebranchweb%/$develop_branch}
        echo ""
        echo "* Try open this: " $basebranchweb/$release_branch
        echo -n "  Is it ok? (Y/n): "
        read yn
        if test -z "$yn" -o "$yn" = "y" -o "$yn" = "Y"; then
            break;
        fi
    done
    git config trello.branch.develop "$develop_branch"
    git config trello.branch.release "$release_branch"
    git config trello.basebranchweb "$basebranchweb"
    echo ""
    echo "* You settings are stored git local config. check this,"
    echo ""
    echo "  git config -l | grep trello"
    echo ""
    git config -l | grep trello
    echo ""
    echo "* Anytime you want to change those values, just run"
    echo ""
    echo "  git tr init"
    echo ""
}

create() {
    load_settings
    mode="$1"
    shift
    trellourl="$1"
    if test "${trellourl#http}" != "${trellourl}"; then
        ## EX) https://trello.com/c/0x1UMRbn1/123-this-is-test-card
        urllen=${#trellourl}
        trid="${trellourl#*://*/*/}"
        len1=${#trid}
        trid=${trid%%/*}
        len2=${#trid}
        len3=$(expr $urllen - $len1 + 1 + $len2)
        trellourl="${trellourl:0:$len3}"
    else
        echo "Usage: git tr $mode https://trello.com/..."
        exit 1
    fi
    br="$mode/$trid"
    if test "$mode" = "feature"; then
        basebr="$develop_branch"
    else
        basebr="$release_branch"
    fi
    echo "* Trying to create branch $br from $basebr"
    git checkout -b $br $basebr || exit
    echo ""
    git config branch."$br".trello "$trellourl" || exit
}

commit() {
    branch=$(current_branch)
    trellourl=$(git config --get branch."$branch".trello)
    if test -z "$trellourl"; then
        echo "Can't determine trello url, set trellourl"
        echo "Usage: git config branch."$branch".trello URL"
        exit 1
    fi
    echo "Trello url: $trellourl"
    gitdir=$(git_dir)
    mkdir "$gitdir/MSGTEMPLATES" 2>/dev/null
    msgtemplate="$gitdir/MSGTEMPLATES/$$.txt"
    echo -e "\n\n$trellourl" > "$msgtemplate"
    git commit -v -t "$msgtemplate" "$@"
}

push() {
    branch=$(current_branch)
    trellourl=$(git config --get branch."$branch".trello)
    git push -u origin "$branch" "$@"
    echo -e "\n$trellourl\n"
}

help() {
    echo "Help!"
}

show() {
    load_settings
    branch=$(current_branch)
    trellourl=$(git config --get branch."$branch".trello)
    echo ""
    echo "Base branch for features: $develop_branch"
    echo "Base branch for hotfixes: $release_branch"
    echo "Base branch view url    : $basebranchweb"
    echo ""
    echo "Current branch: $branch"
    echo "Current trello: $trellourl"
    echo ""
}

case "$1" in
    i|init)
        init
        ;;
    help)
        help
        ;;
    f|feature)
        shift
        create feature "$@"
        ;;
    h|hotfix)
        shift
        create hotfix "$@"
        ;;
    c|commit)
        shift
        commit "$@"
        ;;
    p|push)
        shift
        push "$@"
        ;;
    "")
        show
        ;;
    *)
        echo "Unkown command $1"
        exit 1
        ;;
esac
